######################################################################
# Automatically generated by qmake (3.1) Thu Apr 6 22:51:10 2017
######################################################################
QT += core
QT -= gui

CONFIG += c++11

TARGET = PCMM
CONFIG += console
CONFIG -= app_bundle

TEMPLATE = app

INCLUDEPATH += . \
               sourceCode/Common/ \
               sourceCode/Configure/ \
               sourceCode/SshWrapper/ \
               sourceCode/TraceLog/ \
               sourceCode/include

# Input
HEADERS += sourceCode/Common/App.h \
           sourceCode/Common/LocalTime.h \
           sourceCode/Common/remove_character.h \
           sourceCode/Common/replace_character.h \
           sourceCode/Configure/Configure.h \
           sourceCode/Configure/Configure_Define.h \
           sourceCode/Configure/ExceptionConfigure.h \
           sourceCode/Configure/TraceLogConfigure.h \
           sourceCode/SshWrapper/ISshClient.h \
           sourceCode/SshWrapper/ISshClientSession.h \
           sourceCode/SshWrapper/ISshShellChannel.h \
           sourceCode/SshWrapper/SshClient.h \
           sourceCode/SshWrapper/SshClientSession.h \
           sourceCode/SshWrapper/SshConfigure.h \
           sourceCode/SshWrapper/SshShellChannel.h \
           sourceCode/TraceLog/Trace.h \
           sourceCode/TraceLog/TraceBuf.h \
           sourceCode/TraceLog/TraceConsole.h \
           sourceCode/TraceLog/TraceFile.h
SOURCES += sourceCode/Common/LocalTime.cpp \
           sourceCode/Common/remove_character.cpp \
           sourceCode/Common/replace_character.cpp \
           sourceCode/Configure/Configure.cpp \
           sourceCode/Configure/ExceptionConfigure.cpp \
           sourceCode/Configure/TraceLogConfigure.cpp \
           sourceCode/SshWrapper/SshClient.cpp \
           sourceCode/SshWrapper/SshClientSession.cpp \
           sourceCode/SshWrapper/SshShellChannel.cpp \
           sourceCode/SshWrapperTest/SshOneTimeShellCmdMainTest.cpp


win32:CONFIG(release, debug|release): LIBS += -L$$PWD/sourceCode/static_lib/ -lssh.dll
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/sourceCode/static_lib/ -lssh.dll

INCLUDEPATH += $$PWD/sourceCode/static_lib
DEPENDPATH += $$PWD/sourceCode/static_lib
DLLDESTDIR += $$PWD/sourceCode/dynamic_lib/ssh
