VPATH = ../common
EXObject = $(patsubst %, %/*.o, $(VPATH))
CPPINCLUDE = ../include

CCfile := $(wildcard *.cpp)
Objects = $(CCfile:%.cpp=%.o) 
TARGET = unit_test_parser.elf
CCCMD = cc 
override CFLAGS += $(patsubst %, -I %, $(subst :, ,$(CPPINCLUDE)))

target: $(TARGET)
%.elf: $(Objects) 
	g++ $(Objects) -o $(TARGET) 
%.o: %.cpp
	g++ -c $< -o $@

# backup the cc file
$(foreach v, $(CCfile), $(shell cp $(v) .$(v).bak))


#.PHONY: clean
#clean:
#	-rm $(TARGET) $(Objects)
